import { useState } from "react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import type { GenerateResponse } from "../api";
import { IconCopy, IconCheck, IconDownload, IconInfo, IconBox } from "../icons";

interface Props {
  result: GenerateResponse;
}

// Map our language keys to Prism language identifiers.
const PRISM_LANG: Record<string, string> = {
  python: "python",
  javascript: "javascript",
  typescript: "typescript",
  java: "java",
  cpp: "cpp",
  "c++": "cpp",
  go: "go",
  rust: "rust",
  sql: "sql",
};

export default function CodeOutput({ result }: Props) {
  const [copied, setCopied] = useState(false);

  const lineCount = result.code.split("\n").length;

  function copy() {
    navigator.clipboard.writeText(result.code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }

  function download() {
    const blob = new Blob([result.code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = result.filename || "solution.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="card output">
      <div className="output-header">
        <span className="traffic">
          <i />
          <i />
          <i />
        </span>
        <span className="filename">
          {result.filename}
          <span className="lang-badge">{result.language}</span>
        </span>
        <span className="loc">{lineCount} lines</span>
        <div className="output-actions">
          <button className="btn ghost" onClick={copy}>
            {copied ? <IconCheck /> : <IconCopy />}
            {copied ? "Copied" : "Copy"}
          </button>
          <button className="btn ghost" onClick={download}>
            <IconDownload />
            Download
          </button>
        </div>
      </div>

      <div className="code-scroll">
        <SyntaxHighlighter
          language={PRISM_LANG[result.language] || "text"}
          style={oneDark}
          customStyle={{
            margin: 0,
            borderRadius: 0,
            background: "transparent",
            fontSize: "0.84rem",
            padding: "16px 6px",
          }}
          codeTagProps={{ style: { fontFamily: "var(--mono)" } }}
          showLineNumbers
        >
          {result.code}
        </SyntaxHighlighter>
      </div>

      {result.explanation && (
        <div className="section-block">
          <h4>
            <IconInfo />
            Explanation
          </h4>
          <p>{result.explanation}</p>
        </div>
      )}

      {result.dependencies.length > 0 && (
        <div className="section-block">
          <h4>
            <IconBox />
            Dependencies
          </h4>
          <div className="dep-tags">
            {result.dependencies.map((d) => (
              <span key={d} className="tag">
                {d}
              </span>
            ))}
          </div>
        </div>
      )}

      <div className="model-note">
        Generated by <code>{result.model}</code>
        <span>·</span>
        {result.persisted ? (
          <span className="saved">saved to history</span>
        ) : (
          <span className="unsaved">not saved (DB offline)</span>
        )}
      </div>
    </div>
  );
}
