import { useState } from "react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import type { GenerateResponse } from "../api";

interface Props {
  result: GenerateResponse;
}

// Map our language keys to Prism language identifiers.
const PRISM_LANG: Record<string, string> = {
  python: "python",
  javascript: "javascript",
  typescript: "typescript",
  java: "java",
  cpp: "cpp",
  "c++": "cpp",
  go: "go",
  rust: "rust",
  sql: "sql",
};

export default function CodeOutput({ result }: Props) {
  const [copied, setCopied] = useState(false);

  function copy() {
    navigator.clipboard.writeText(result.code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }

  function download() {
    const blob = new Blob([result.code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = result.filename || "solution.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="card output">
      <div className="output-header">
        <span className="filename">{result.filename}</span>
        <div className="output-actions">
          <button className="btn ghost" onClick={copy}>
            {copied ? "Copied ✓" : "Copy"}
          </button>
          <button className="btn ghost" onClick={download}>
            Download
          </button>
        </div>
      </div>

      <SyntaxHighlighter
        language={PRISM_LANG[result.language] || "text"}
        style={oneDark}
        customStyle={{ margin: 0, borderRadius: 0, fontSize: "0.85rem" }}
        showLineNumbers
      >
        {result.code}
      </SyntaxHighlighter>

      {result.explanation && (
        <div className="explanation">
          <h4>Explanation</h4>
          <p>{result.explanation}</p>
        </div>
      )}

      {result.dependencies.length > 0 && (
        <div className="deps">
          <h4>Dependencies</h4>
          <div className="dep-tags">
            {result.dependencies.map((d) => (
              <span key={d} className="tag">
                {d}
              </span>
            ))}
          </div>
        </div>
      )}

      <div className="model-note">
        Generated by <code>{result.model}</code>
        {result.persisted ? " · saved to history" : " · not saved (DB offline)"}
      </div>
    </div>
  );
}
